- Documentation:
    - GitLab Docs:
        - href: https://docs.gitlab.com/
          icon: gitlab
    - Nexus Docs:
        - href: https://help.sonatype.com/en/sonatype-nexus-repository.html
          icon: nexus
    - Traefik Docs:
        - href: https://doc.traefik.io/traefik/
          icon: traefik
    - Prometheus Docs:
        - href: https://prometheus.io/docs/
          icon: prometheus
    - Grafana Docs:
        - href: https://grafana.com/docs/grafana/latest/
          icon: grafana
    - MinIO Docs:
        - href: https://min.io/docs/minio/linux/index.html
          icon: minio
    - Vault Docs:
        - href: https://developer.hashicorp.com/vault/docs
          icon: vault
    - Loki Docs:
        - href: https://grafana.com/docs/loki/latest/
          icon: loki
